### Get all contacts
GET http://localhost:3000/contacts

### Get one contact by id (replace with actual MongoDB ID from your database)
GET http://localhost:3000/contacts/[id]

###_testing on Render (after deployment)
GET https://cse341-rtep.onrender.com/contacts/[id]

GET https://cse341-rtep.onrender.com/contacts/
